const API="/api/apps-script";let token=sessionStorage.getItem("pb_token")||"";let me=JSON.parse(sessionStorage.getItem("pb_user")||"null");let data={};
const $=x=>document.getElementById(x), esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])), money=x=>"₱ "+Number(x||0).toLocaleString("en-PH",{minimumFractionDigits:2});
async function api(action,p={}){let r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,token,...p})});let j=await r.json();if(!j.ok)throw Error(j.message||"Request failed");return j.data}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").textContent="";try{let x=await api("login",{username:$("loginUser").value,password:$("loginPass").value});token=x.token;me=x.user;sessionStorage.setItem("pb_token",token);sessionStorage.setItem("pb_user",JSON.stringify(me));start()}catch(e){$("loginError").textContent=e.message}};
function start(){$("loginPage").classList.add("hidden");$("app").classList.remove("hidden");$("accountName").textContent=me.name;document.querySelectorAll(".admin-only").forEach(x=>x.style.display=me.role==="Admin"?"":"none");load();show("dashboard")}
async function load(){try{data=await api("bootstrap");render()}catch(e){alert(e.message)}}
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(id).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));$("sidebar").classList.remove("open")}
document.querySelectorAll(".nav").forEach(x=>x.onclick=()=>show(x.dataset.page));$("menuBtn").onclick=()=>$("sidebar").classList.toggle("open");$("logoutBtn").onclick=()=>{sessionStorage.clear();location.reload()};
function render(){renderDash();renderProducts();renderIn();renderOut();renderSales();renderUsers();$("storeName").value=data.settings.name||"Pizza Bianos";$("storeAddress").value=data.settings.address||"";$("storeContact").value=data.settings.contact||""}
function today(){return new Date().toISOString().slice(0,10)}
function renderDash(){let td=today(),ins=data.stockIn.filter(x=>x.date.slice(0,10)===td).reduce((a,x)=>a+Number(x.quantity),0),outs=data.stockOut.filter(x=>x.date.slice(0,10)===td).reduce((a,x)=>a+Number(x.quantity),0),sales=data.sales.filter(x=>x.date.slice(0,10)===td).reduce((a,x)=>a+Number(x.total),0),low=data.products.filter(x=>+x.quantity<=+x.reorder).length;$("dProducts").textContent=data.products.length;$("dLow").textContent=low;$("dIn").textContent=ins;$("dOut").textContent=outs;$("dSales").textContent=money(sales);let top=[...data.products].sort((a,b)=>b.quantity-a.quantity).slice(0,6);$("stockChart").innerHTML=top.map(p=>`<div class="bar"><i style="height:${Math.max(20,Math.min(170,+p.quantity*2))}px"></i>${esc(p.name)}</div>`).join("");let tx=[...data.stockIn.map(x=>({t:"Stock In - "+x.product,d:x.date})),...data.stockOut.map(x=>({t:"Stock Out - "+x.product,d:x.date})),...data.sales.map(x=>({t:"Sales - "+x.invoice,d:x.date}))].sort((a,b)=>b.d.localeCompare(a.d)).slice(0,5);$("recentTransactions").innerHTML=tx.map(x=>`<div class="transaction"><span>${esc(x.t)}</span><span>${esc(x.d)}</span><button class="btn">View</button></div>`).join("")}
function renderProducts(){$("productsTable").innerHTML=data.products.map(p=>`<tr><td>${esc(p.id)}</td><td>${esc(p.name)}</td><td>${esc(p.category)}</td><td>${esc(p.supplier)}</td><td>${p.quantity}</td><td>${esc(p.unit)}</td><td>${p.reorder}</td><td>${me.role==="Admin"?`<button onclick="productForm('${p.id}')">Edit</button> <button onclick="delProduct('${p.id}')">Delete</button>`:"—"}</td></tr>`).join("")}
function renderIn(){$("stockInTable").innerHTML=data.stockIn.slice().reverse().map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.date)}</td><td>${esc(x.product)}</td><td>${x.quantity} ${esc(x.unit)}</td><td>${esc(x.supplier)}</td><td>${esc(x.receivedBy)}</td><td><button>View</button></td></tr>`).join("")}
function renderOut(){$("stockOutTable").innerHTML=data.stockOut.slice().reverse().map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.date)}</td><td>${esc(x.product)}</td><td>${esc(x.customer)}</td><td>${x.quantity} ${esc(x.unit)}</td><td>${esc(x.usedFor)}</td><td>${esc(x.requestedBy)}</td><td><button>View</button></td></tr>`).join("")}
function renderSales(){$("salesTable").innerHTML=data.sales.slice().reverse().map(x=>`<tr><td>${esc(x.invoice)}</td><td>${esc(x.date)}</td><td>${esc(x.customer)}</td><td>${x.items}</td><td>${money(x.total)}</td><td>${esc(x.payment)}</td><td><button>View</button></td></tr>`).join("")}
function renderUsers(){if(me.role!=="Admin")return;$("usersTable").innerHTML=data.users.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.username)}</td><td>${esc(x.role)}</td><td>${esc(x.status)}</td><td><button onclick="toggleUser('${esc(x.username)}')">Edit</button> <button onclick="toggleUser('${esc(x.username)}')">${x.status==="Active"?"Disable":"Enable"}</button></td></tr>`).join("")}
function form(title,fields,fn){$("modalTitle").textContent=title;$("modalForm").innerHTML=`<div class="form-grid">${fields.map(f=>`<label>${f.label}<input id="f_${f.key}" type="${f.type||"text"}" value="${esc(f.value||"")}" ${f.required?"required":""}></label>`).join("")}<button class="btn dark" type="submit">Save</button></div>`;$("modal").classList.remove("hidden");$("modalForm").onsubmit=async e=>{e.preventDefault();let o={};fields.forEach(f=>o[f.key]=$("f_"+f.key).value);try{await fn(o);closeModal();load()}catch(e){alert(e.message)}}}
function closeModal(){$("modal").classList.add("hidden")}
function productForm(id){let p=data.products.find(x=>x.id===id)||{};form(id?"Edit Product":"Add Product",[{key:"id",label:"ID",value:p.id},{key:"name",label:"Product Name",value:p.name,required:true},{key:"category",label:"Category",value:p.category||"Ingredients"},{key:"supplier",label:"Supplier",value:p.supplier||"Supplier A"},{key:"quantity",label:"Quantity",type:"number",value:p.quantity||0},{key:"unit",label:"Unit",value:p.unit||"pcs"},{key:"reorder",label:"Reorder Level",type:"number",value:p.reorder||5}],o=>api("saveProduct",{product:o}))}
async function delProduct(id){if(confirm("Delete product?")){await api("deleteProduct",{id});load()}}
function stockInForm(){form("Stock In",[{key:"productId",label:"Product",value:data.products[0]?.id,required:true},{key:"quantity",label:"Quantity",type:"number",value:1,required:true},{key:"supplier",label:"Supplier",value:"Supplier A"},{key:"date",label:"Date",value:today()}],o=>api("stockIn",{item:o}))}
function stockOutForm(){form("Stock Out",[{key:"productId",label:"Product",value:data.products[0]?.id,required:true},{key:"quantity",label:"Quantity",type:"number",value:1,required:true},{key:"customer",label:"Customer",value:"Walk-in Customer"},{key:"usedFor",label:"Used For",value:"Order"},{key:"date",label:"Date",value:today()}],o=>api("stockOut",{item:o}))}
function saleForm(){form("New Sale",[{key:"productId",label:"Product",value:data.products[0]?.id,required:true},{key:"quantity",label:"Quantity",type:"number",value:1,required:true},{key:"customer",label:"Customer",value:"Walk-in Customer"},{key:"payment",label:"Payment",value:"Cash"}],o=>api("sale",{item:o}))}
function userForm(){form("Add User",[{key:"username",label:"Username",required:true},{key:"name",label:"Name",required:true},{key:"password",label:"Password",type:"password",required:true},{key:"role",label:"Role",value:"Staff"}],o=>api("saveUser",{user:o}))}
async function toggleUser(username){if(confirm("Change user status?")){await api("toggleUser",{username});load()}}
async function saveSettings(){try{await api("settings",{settings:{name:$("storeName").value,address:$("storeAddress").value,contact:$("storeContact").value}});$("settingsMsg").textContent="Settings saved."}catch(e){$("settingsMsg").textContent=e.message}}
function report(type){let rows=[];if(type==="stock"||type==="low")rows=data.products.filter(x=>type==="stock"||+x.quantity<=+x.reorder).map(x=>[x.id,x.name,x.category,x.quantity,x.unit,x.reorder]);if(type==="in")rows=data.stockIn.map(x=>[x.id,x.date,x.product,x.quantity,x.supplier]);if(type==="out")rows=data.stockOut.map(x=>[x.id,x.date,x.product,x.quantity,x.customer,x.usedFor]);if(type==="sales")rows=data.sales.map(x=>[x.invoice,x.date,x.customer,x.items,money(x.total),x.payment]);if(type==="summary")rows=[["Products",data.products.length],["Low Stock",data.products.filter(x=>+x.quantity<=+x.reorder).length],["Stock In Transactions",data.stockIn.length],["Stock Out Transactions",data.stockOut.length],["Sales",money(data.sales.reduce((a,x)=>a+Number(x.total),0))]];$("reportOutput").classList.remove("hidden");$("reportOutput").innerHTML="<h3>"+type.toUpperCase()+" REPORT</h3>"+rows.map(r=>"<div class='transaction'>"+r.map(esc).join(" &nbsp; | &nbsp; ")+"</div>").join("")}
if(token&&me)start();